name: Build Docs # and Deploy

on:
  workflow_dispatch: # Manual trigger

# permissions:
#   contents: write  # Required to push to gh-pages branch

jobs:
  build-docs:
    name: Build Documentation # and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --with docs

      - name: Generate API docs
        run: |
          poetry run sphinx-apidoc -o docs/api src/quantum_executor

      - name: Build HTML
        run: |
          poetry run sphinx-build -b html docs docs/_build/html # -W

    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v4
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: docs/_build/html
    #       publish_branch: gh-pages
    #       force_orphan: true  # Clean history for the docs branch
